TREATY = 'treaty'
COP_DECISION = 'decision'
COURT_DECISION = 'court_decision'
LITERATURE = 'literature'
LEGISLATION = 'legislation'

DOC_TYPE = (
    (TREATY, "Treaty"),
    (COP_DECISION, "Decision"),
    (LITERATURE, "Literature"),
    (COURT_DECISION, "Court Decision"),
    (LEGISLATION, "Legislation"),
)

DOC_SOURCES = {
    TREATY: 'IUCN',
    COP_DECISION: 'InforMEA',
    LITERATURE: 'IUCN',
    COURT_DECISION: 'InforMEA',
    LEGISLATION: 'FAO',
}

TREATY_FILTERS = {
    'trTypeOfText_en': 'tr_type',
    'trFieldOfApplication_en': 'tr_field',
    'trStatus': 'tr_status',
    'trPlaceOfAdoption': 'tr_place_of_adoption',
    'trDepository_en': 'tr_depository',
}

DECISION_FILTERS = {
    'decType': 'dec_type',
    'decStatus': 'dec_status',
    'decTreatyId': 'dec_treaty',
}

LITERATURE_FILTERS = {
    'litTypeOfText': 'lit_type',
    'litAuthor': 'lit_author',
    'litSerialTitle': 'lit_serial',
    'litPublisher': 'lit_publisher',
}

COURT_DECISION_FILTERS = {
    'cdTerritorialSubdivision': 'cd_territorial_subdivision',
    'cdTypeOfText': 'cd_type',
}

LEGISLATION_FILTERS = {
    'legType_en': 'leg_type',
    'legTerritorialSubdivision': 'leg_territorial',
    'legStatus': 'leg_status',
}

DOC_TYPE_FILTER_MAPPING = {
    TREATY: TREATY_FILTERS,
    COP_DECISION: DECISION_FILTERS,
    LITERATURE: LITERATURE_FILTERS,
    COURT_DECISION: COURT_DECISION_FILTERS,
    LEGISLATION: LEGISLATION_FILTERS,
}

FIELD_TO_FACET_MAPPING = {
    'tr_type': 'trTypeOfText_en',
    'tr_field': 'trFieldOfApplication_en',
    'tr_status': 'trStatus',
    'tr_place_of_adoption': 'trPlaceOfAdoption',
    'tr_depository': 'trDepository_en',

    'dec_type': 'decType',
    'dec_status': 'decStatus',
    'dec_treaty': 'decTreatyId',

    'lit_type': 'litTypeOfText',
    'lit_author': 'litAuthor',
    'lit_serial': 'litSerialTitle',
    'lit_publisher': 'litPublisher',

    'cd_territorial_subdivision': 'cdTerritorialSubdivision',
    'cd_type': 'cdTypeOfText',

    'leg_type': 'legType_en',
    'leg_territorial': 'legTerritorialSubdivision',
    'leg_status': 'legStatus',

    'subject': 'docSubject',
    'keyword': 'docKeyword',
    'country': 'docCountry',
    'region': 'docRegion',
    'language': 'docLanguage',
}

OPERATION_FIELD_MAPPING = {
    'tr_depository_op': 'tr_depository',
    'lit_author_op': 'lit_author',
    'subject_op': 'subject',
    'keyword_op': 'keyword',
    'country_op': 'country',
    'region_op': 'region',
    'language_op': 'language',
}

SOLR_FIELDS = [
    'id', 'type', 'source',

    'trPaperTitleOfText', 'trPaperTitleOfTextFr', 'trPaperTitleOfTextSp',
    'trPaperTitleOfTextOther', 'trTitleOfTextShort', 'trElisId',
    'trJurisdiction', 'trPlaceOfAdoption', 'trDateOfText', 'trDateOfEntry',
    'trDateOfModification', 'trIntroText',

    'decTitleOfText', 'decNumber', 'decStatus', 'decPublishDate',
    'decUpdateDate', 'decBody',


    'legTitle', 'legLongTitle', 'legCountry_en', 'legDate', 'legStatus',


    'cdTitleOfText_en', 'cdTitleOfText_es', 'cdTitleOfText_fr', 'cdDateOfText',
    'cdAbstract_en',

    'litLongTitle', 'litLongTitle_fr', 'litLongTitle_sp', 'litLongTitle_other',
    'litPaperTitleOfText', 'litPaperTitleOfText_fr', 'litPaperTitleOfText_sp',
    'litPaperTitleOfText_other', 'litTitleOfTextShort',
    'litTitleOfTextShort_fr', 'litTitleOfTextShort_sp',
    'litTitleOfTextShort_other', 'litTitleOfTextTransl',
    'litTitleOfTextTransl_fr', 'litTitleOfTextTransl_sp', 'litAuthor',
    'litCorpAuthor', 'litPublisher', 'litPublPlace', 'litDateOfEntry',
    'litDateOfModification', 'litKeyword',
]

LANGUAGE_MAP = {
    'en': 'English',
    'es': 'Spanish',
    'fr': 'French',
    'ru': 'Russian',
}

FIELDS_BY_TYPE = {
    TREATY: [
        'id', 'type', 'source',
        'trElisId',
        'trInformeaId',
        'trDateOfEntry',
        'trDateOfModification',
        'trDateOfText',
        'trSearchDate',
        'trPaperTitleOfText',
        'trPaperTitleOfTextSp',
        'trPaperTitleOfTextFr',
        'trPaperTitleOfTextOther',
        'trTypeOfText',
        'trJurisdiction',
        'trFieldOfApplication',
        'trSubject',
        'trLanguageOfDocument',
        'trObsolete',
        'trEnabledByTreaty',
        'trPlaceOfAdoption',
        'trDepository',
        'trEntryIntoForceDate',
        'trKeyword',
        'trAbstract',
        'trComment',
        'trTitleOfTextShort',
        'trAuthor',
        'trTitleAbbreviation',
        'trFieldOfApplication',
        'trPlaceOfAdoption',
        'trBasin',
        'trCitiesTreaty',
        'trConfName',
        'trContributor',
        'trCourtName',
        'trDateOfLastLegalAction',
        'trLinkToFullText',
        'trLinkToFullTextSp',
        'trLinkToFullTextFr',
        'trLinkToFullTextOther',
        'trLinkToAbstract',
        'trObsolete',
        'trRegion',
        'trRelevantTextTreaty',
        'trScope',
        'trSearchDate',
        'trSeatOfCourt',
        'trSupersedesTreaty',
        'trAmendsTreaty',
        'trCitesTreaty',
        'trAvailableIn',
        'trLanguageOfTranslation',
        'trNumberOfPages',
        'trOfficialPublication',
        'trInternetReference',
        'trDateOfConsolidation',
    ],
    COP_DECISION: [
        'id', 'type', 'source',
        'decId',
        'decLink',
        'decShortTitle',
        'decLongTitle',
        'decKeyword',
        'decSummary',
        'decBody',
        'decType',
        'decStatus',
        'decNumber',
        'decTreaty',
        'decTreatyId',
        'decPublishDate',
        'decUpdateDate',
        'decMeetingId',
        'decMeetingTitle',
        'decMeetingUrl',
    ],
    LITERATURE: [
        'id', 'type', 'source',
        'litId',
        'litAuthor',
        'litCorpAuthor',
        'litDateOfEntry',
        'litDateOfModification',
        'litTitleAbbreviation',
        'litLongTitle',
        'litLongTitle_fr',
        'litLongTitle_sp',
        'litLongTitle_other',
        'litPaperTitleOfText',
        'litPaperTitleOfText_fr',
        'litPaperTitleOfText_sp',
        'litPaperTitleOfText_other',
        'litTitleOfTextShort',
        'litTitleOfTextShort_fr',
        'litTitleOfTextShort_sp',
        'litTitleOfTextShort_other',
        'litTitleOfTextTransl',
        'litTitleOfTextTransl_fr',
        'litTitleOfTextTransl_sp',
        'litSerialTitle',
        'litISBN',
        'litPublisher',
        'litPublPlace',
        'litVolumeNo',
        'litCollation',
        'litDateOfText',
        'litLinkToFullText',
        'litTypeOfText',
        'litTypeOfText_fr',
        'litTypeOfText_sp',
        'litLanguageOfDocument',
        'litLanguageOfDocument_fr',
        'litLanguageOfDocument_sp',
        'litSubject',
        'litSubject_fr',
        'litSubject_sp',
        'litKeyword',
        'litKeyword_fr',
        'litKeyword_sp',
        'litScope',
        'litScope_fr',
        'litScope_sp',
        'litIntOrg',
        'litIntOrg_fr',
        'litIntOrg_sp',
        'litCountry',
        'litCountry_fr',
        'litCountry_sp',
        'litDisplayTitle',
        'litDisplayDetails',
        'litDisplayRegion',
        'litDisplayRegion_fr',
        'litDisplayRegion_sp',
        'litLanguageOfTranslation',
        'litLanguageOfTranslation_fr',
        'litLanguageOfTranslation_sp',
        'litRegion',
        'litRegion_fr',
        'litRegion_sp',
        'litAbstract',
        'litAbstract_fr',
        'litAbstract_sp',
        'litAbstract_other',
        'litLinkToAbstract',
        'litLocation',
        'litAvailableIn',
        'litSeriesFlag',
        'litSerialStatus',
        'litFormerTitle',
        'litModeOfAcquisition',
        'litFrequency',
        'litHoldings',
        'litSearchDate',
        'litRelatedWebSite',
        'litContributor',
        'litISSN',
        'litConfName',
        'litConfName_fr',
        'litConfName_sp',
        'litConfName_other',
        'litConfNo',
        'litConfPlace',
        'litConfDate',
        'litDateOfTextSer',
        'litTerritorialSubdivision',
        'litTerritorialSubdivision_fr',
        'litTerritorialSubdivision_sp',
        'litEdition',
        'litCallNo',
        'litRelatedMonograph',
        'litBasin',
        'litBasin_fr',
        'litBasin_sp',
        'litInternetReference',
        'litTreatyReference',
        'litCourtDecisionReference',
        'litLiteratureReference',
        'litFaolexReference',
        'litEULegislationReference',
        'litNationalLegislationReference',
    ],
    COURT_DECISION: [
        'id', 'type', 'source',
        'cdTitleOfText',
        'cdAbstract_en',
        'cdAbstract_fr',
        'cdAbstract_es',
        'cdAlternativeRecordId',
        'cdSeatOfCourt_en',
        'cdSeatOfCourt_fr',
        'cdSeatOfCourt_es',
        'cdCountry_en',
        'cdCountry_fr',
        'cdCountry_es',
        'cdCourtDecisionIdNumber',
        'cdCourtDecisionSubdivision',
        'cdCourtName',
        'cdDateOfEntry',
        'cdDateOfModification',
        'cdStatusOfDecision',
        'cdSubject',
        'cdEcolexUrl',
        'cdFaolexUrl',
        'cdFiles',
        'cdInformeaTags',
        'cdInternetReference_en',
        'cdInternetReference_fr',
        'cdInternetReference_es',
        'cdIsisNumber',
        'cdJurisdiction',
        'cdJustices',
        'cdNumberOfPages',
        'cdOriginalId',
        'cdReferenceNumber',
        'cdReferenceToLegislation',
        'cdRelatedUrl_en',
        'cdRelatedUrl_fr',
        'cdRelatedUrl_es',
        'cdLanguageOfDocument',
        'cdTerritorialSubdivision',
        'cdTypeOfText',
        'cdLinkToFullText_en',
        'cdLinkToFullText_fr',
        'cdLinkToFullText_es',
        'cdNotes',
        'cdAbstractOther',
        'cdAvailableIn',
        'cdCourtDecisionReference',
        'cdKeywords',
        'cdFaolexReference',
        'cdInstance',
        'cdOfficialPublication',
        'cdRegion',
        'cdTitleOfTextOther',
        'cdTitleOfTextShort',
        'cdTreatyReference',
        'cdUrlOther',
        'cdDateOfText',
    ],
    LEGISLATION: [
        'id', 'type', 'source', 'legId',
        'legId',
        'legTitle',
        'legLongTitle',
        'legSource',
        'legDate',
        'legOriginalDate',
        'legModificationDate',
        'legConsolidationDate',
        'legEntryDate',
        'legSearchDate',
        'legEntryIntoForce',
        'legCountry_iso',
        'legCountry_en',
        'legCountry_fr',
        'legCountry_es',
        'legTerritorialSubdivision',
        'legGeoArea_en',
        'legGeoArea_fr',
        'legGeoArea_es',
        'legTypeCode',
        'legType_en',
        'legType_fr',
        'legType_es',
        'legRelatedWebSite',
        'legLanguage_code',
        'legLanguage_en',
        'legLanguage_fr',
        'legLanguage_es',
        'legAbstract',
        'legSubject_code',
        'legSubject_en',
        'legSubject_fr',
        'legSubject_es',
        'legKeyword_code',
        'legKeyword_en',
        'legKeyword_fr',
        'legKeyword_es',
        'legImplement',
        'legAmends',
        'legRepeals',
    ],
}
